src/Seafood/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Seafood.Models;
using Microsoft.AspNetCore.Identity;

namespace Seafood.Controllers
{
    public class ItemController : Controller
    {
        private SeafoodDbContext db = new SeafoodDbContext();

        public IActionResult Index()
        {
            return View(db.Items.ToList());
        }

        public IActionResult Detail(int id)
        {
            var thisItem = db.Items.FirstOrDefault(items => items.ItemId == id);
            return View(thisItem);
        }

        //    public IActionResult Create()
        //    {
        //        return View();
        //    }
        //    [HttpPost]
        //    public IActionResult Create(Item item)
        //    {
        //        db.Items.Add(item);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    public IActionResult Edit(int id)
        //    {
        //        var thisItem = db.Items.FirstOrDefault(items => items.ItemId == id);
        //        return View(thisItem);
        //    }
        //    [HttpPost]
        //    public IActionResult Edit(Item item)
        //    {
        //        db.Entry(item).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    public ActionResult Delete(int id)
        //    {
        //        var thisItem = db.Items.FirstOrDefault(items => items.ItemId == id);
        //        return View(thisItem);
        //    }

        //    [HttpPost, ActionName("Delete")]
        //    public IActionResult DeleteConfirmed(int id)
        //    {
        //        var thisItem = db.Items.FirstOrDefault(items => items.ItemId == id);
        //        db.Items.Remove(thisItem);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
    }
}

src/Seafood/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="//cdn.muicss.com/mui-0.9.21/css/mui.min.css" rel="stylesheet" type="text/css" />
        <script src="//cdn.muicss.com/mui-0.9.21/js/mui.min.js"></script>
        <script src="//code.jquery.com/jquery-2.1.4.min.js"></script>
        <script src="~/js/Scripts.js"></script>
        <link href="~/CSS/StyleSheet.css" rel="stylesheet" />
        <script src="https://use.fontawesome.com/c3a95916f1.js"></script>
        <title>@ViewBag.Title</title>
    </head>
    <body>
        <div id="sidedrawer">
            <div id="sidedrawer-brand"  >
                <img src="~/images/cod.png" width="185" />
                <p class="mui--text-center"> @Html.ActionLink("HOME", "Index", "Home") </p>
            </div>
            <div class="mui-divider"></div>
            <ul>
                <li>
                    <strong>LEARN ABOUT OUR OPERATIONS</strong>
                    <ul>
                        <li class="list-group-item">@Html.ActionLink("Products", "Index", "Item")</li>
                        <li class="list-group-item">@Html.ActionLink("Sign Up for our Newsletter", "Create", "Subscriber")</li>
                        <li class="list-group-item">@Html.ActionLink("Delivery", "Delivery", "Home")</li>
                        <li class="list-group-item">@Html.ActionLink("About Us", "About", "Home")</li>
                    </ul>
                </li>
                <li>
                    <strong>@Html.ActionLink("ADMIN PORTAL", "Index", "Account")</strong>
                </li>
            </ul>
        </div>
        <header id="header">
            <div class="mui-appbar mui--appbar-line-height">
                <div class="mui-container-fluid">
                    <a class="sidedrawer-toggle mui--visible-xs-inline-block mui--visible-sm-inline-block js-show-sidedrawer">☰</a>
                    <a class="sidedrawer-toggle mui--hidden-xs mui--hidden-sm js-hide-sidedrawer">☰</a>
                    <span class="mui--text-title">Son of Cod: For all your seafood needs.</span>
                </div>
            </div>
        </header>
        <div id="content-wrapper">
            <div class="mui--appbar-height"></div>
            <div class="mui-container-fluid">
                <br />
                <div class="mui--text-right">
                    <img src="~/images/sonofcod.png" width="250" alt="Son of Cod Logo" />
                    <div class="mui-divider"></div>
                </div>
                @RenderBody()
            </div>
        </div>
        <footer id="footer">
            <div class="mui-container-fluid">
                <br>
                <p>Son of Cod Fishing Company <i class="fa fa-copyright fa-fw" aria-hidden="true"></i>2017   | Made with ♥ by <a href="https://www.muicss.com">MUI</a> |   @Html.ActionLink("HOME", "Index", "Home")</p>
            </div>
        </footer>
    </body>
</html>